red-hat-data-services/kserve

python/kserve/setup.cfg

Fixes #
- Logs
**Checklist**:
```release-note
```

Add name and version in setup.cfg file to support CPaaS

---

python/kserve/requirements.txt

Fixes #
- Logs
**Checklist**:
```release-note
```

Add hash for dependencies

---

python/kserve/requirements.txt

Fixes #
- Logs
**Checklist**:
```release-note
```

Fix requirements.txt file

---

python/kserve/poetry.lock
python/kserve/pyproject.toml

Fixes #
- Logs
**Checklist**:
```release-note
```

Downgrade py-spy to "0.3.12"

---

python/kserve/requirements.txt

Fixes #
- Logs
**Checklist**:
```release-note
```

fetching pywin32 dependency from github

---

kserve.iml

**What this PR does / why we need it:**
This is an empty PR, just to trigger openshift-ci builds.

Empty-Commit: Trigger 1.33 builds

---

config/overlays/odh/params.env

Fixes #
- Logs
**Checklist**:
```release-note
```

Update KServe image tags with their SHAs

---

python/kserve/kserve/storage/storage.py

support verify variable with storage-config json style (fix-3263)
It fixes this issue(https://github.com/opendatahub-io/odh-dashboard/issues/2207)

[Cherry-pick] Support verify variable with storage-config json style (fix-3263) 

---

config/overlays/odh/kustomization.yaml
config/overlays/odh/set-resources-manager-patch.yaml

cherry-pick: https://github.com/opendatahub-io/kserve/pull/125

[Cherry-Pick] increase kserve controller limit resources(cpu/memory)

---

config/overlays/odh/params.env

Fixes #
- Logs
**Checklist**:
```release-note
```

Update the image tag to refer latest images of rhoai-2.6

---

.github/workflows/agent-docker-publish.yml
.github/workflows/alibiexplainer-docker-publish.yml
.github/workflows/artexplainer-docker-publish.yml
.github/workflows/custom-model-grpc-publish.yml
.github/workflows/e2e-test.yml
.github/workflows/go.yml
.github/workflows/kserve-controller-docker-publish.yml
.github/workflows/lightgbm-docker-publish.yml
.github/workflows/paddle-docker-publish.yml
.github/workflows/pmml-docker-publish.yml
.github/workflows/python-test.yml
.github/workflows/qpext-docker-publish.yml
.github/workflows/router-docker-publish.yml
.github/workflows/sklearnserver-docker-publish.yml
.github/workflows/storage-initializer-docker-publisher.yml
.github/workflows/tf2openapi-docker-publisher.yml
.github/workflows/transformer-docker-publish.yml
.github/workflows/xgbserver-docker-publisher.yml

This PR will disable all gitactions for 2.6 branch because 2.6 branch will be controlled by openshift-ci.

disable all gitaction for 2.6 branch

---

config/overlays/odh/params.env

Fixes #
- Logs
**Checklist**:
```release-note
```

Update SHAs for KServe images

---

.gitignore

cherry-pick: https://github.com/opendatahub-io/kserve/pull/254

[Cherry-Pick] add .tekton to gitignore to avoid conflict due to Konflux

---

config/overlays/odh/set-resources-manager-patch.yaml

Cherry-pick of https://github.com/opendatahub-io/kserve/pull/259

[rhoai-2.8] Increase memory limit of kserve-controller pod

---

cmd/manager/main.go
python/storage-initializer.Dockerfile

Cherry-pick of:
* https://github.com/opendatahub-io/kserve/pull/260
* https://github.com/opendatahub-io/kserve/pull/265

[rhoai-2.8 ] Cherry-picks - CVE fixes and crashloop fix

---

config/overlays/odh/params.env

Fixes #
- Logs
**Checklist**:
```release-note
```

updating the kserve-router SHA

---

.tekton/kserve-agent-28-push.yaml
.tekton/kserve-controller-28-push.yaml
.tekton/kserve-router-28-push.yaml
.tekton/kserve-storage-initializer-28-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

adding customizations after KFLUXBUGS-1114 fix

---

.github/workflows/instant-merge.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

adding instant-merge workflow for Konflux PRs

---

.tekton/kserve-agent-28-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

check PR auto-merge workflow

---

.github/workflows/instant-merge.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

updating instant-merger

---

.tekton/kserve-agent-29-pull-request.yaml
.tekton/kserve-agent-29-push.yaml
.tekton/kserve-controller-29-pull-request.yaml
.tekton/kserve-controller-29-push.yaml
.tekton/kserve-router-29-pull-request.yaml
.tekton/kserve-router-29-push.yaml
.tekton/kserve-storage-initializer-29-pull-request.yaml
.tekton/kserve-storage-initializer-29-push.yaml
config/overlays/odh/params.env

Fixes #
- Logs
**Checklist**:
```release-note
```

adding tekton changes for 2.9

---

.github/workflows/instant-merge.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

updating instant merger

---

config/overlays/odh/params.env

Fixes #
- Logs
**Checklist**:
```release-note
```

updating agent image

---

config/overlays/odh/params.env

Fixes #
- Logs
**Checklist**:
```release-note
```

update SHA for kserve-storage-initializer

---

.tekton/kserve-agent-29-pull-request.yaml
.tekton/kserve-agent-29-push.yaml
.tekton/kserve-controller-29-pull-request.yaml
.tekton/kserve-controller-29-push.yaml
.tekton/kserve-router-29-pull-request.yaml
.tekton/kserve-router-29-push.yaml
.tekton/kserve-storage-initializer-29-pull-request.yaml
.tekton/kserve-storage-initializer-29-push.yaml
config/overlays/odh/params.env

Fixes #
- Logs
**Checklist**:
```release-note
```

Adding taketon changes for 2.9

---

.tekton/kserve-agent-29-pull-request.yaml
.tekton/kserve-storage-initializer-29-pull-request.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

Updating output image URL for Konflux PR build

---

.tekton/kserve-storage-initializer-29-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

dummy commit for check

---

.tekton/kserve-agent-29-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

dummy commit for agent

---

.tekton/kserve-controller-29-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

dummy commit for controller

---

pkg/apis/serving/v1beta1/inference_service_validation.go
pkg/constants/constants.go
pkg/controller/v1beta1/inferenceservice/components/explainer.go
pkg/controller/v1beta1/inferenceservice/components/predictor.go
pkg/controller/v1beta1/inferenceservice/components/transformer.go
pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go
pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler_test.go
pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go
pkg/controller/v1beta1/inferenceservice/reconcilers/raw/raw_kube_reconciler.go

Cherry-pick of opendatahub-io/kserve#338

Allow disabling creation of the HPA in raw deployment mode (#3086)

---

.tekton/kserve-agent-nightly-pull-request.yaml
.tekton/kserve-agent-nightly-push.yaml
.tekton/kserve-controller-nightly-pull-request.yaml
.tekton/kserve-controller-nightly-push.yaml
.tekton/kserve-router-nightly-pull-request.yaml
.tekton/kserve-router-nightly-push.yaml
.tekton/kserve-storage-initializer-nightly-pull-request.yaml
.tekton/kserve-storage-initializer-nightly-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

update konflux nightly

---

config/overlays/odh/params.env

set image tag to nightly

---

pkg/constants/constants.go
pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go
pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go
pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler_test.go

Cherry-picks https://github.com/kserve/kserve/commit/629e4aee83a5e4b7623de59bcdf1767eb3495d5d.

[RHOAIENG-6577][Cherry-pick][RHOAI-2.8] fix: HPA equality check should include annotations (#3650)

---

.tekton/kserve-agent-pull-request.yaml
.tekton/kserve-controller-pull-request.yaml
.tekton/kserve-router-pull-request.yaml
.tekton/kserve-storage-initializer-pull-request.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

update tekton pull-request

---

.tekton/kserve-agent-29-pull-request.yaml
.tekton/kserve-controller-29-pull-request.yaml
.tekton/kserve-router-29-pull-request.yaml
.tekton/kserve-storage-initializer-29-pull-request.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

Updating base image digest

---

.tekton/kserve-agent-28-pull-request.yaml
.tekton/kserve-controller-28-pull-request.yaml
.tekton/kserve-router-28-pull-request.yaml
.tekton/kserve-storage-initializer-28-pull-request.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

updating base image 2.8

---

.tekton/kserve-agent-210-pull-request.yaml
.tekton/kserve-agent-210-push.yaml
.tekton/kserve-controller-210-pull-request.yaml
.tekton/kserve-controller-210-push.yaml
.tekton/kserve-router-210-pull-request.yaml
.tekton/kserve-router-210-push.yaml
.tekton/kserve-storage-initializer-210-pull-request.yaml
.tekton/kserve-storage-initializer-210-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

onboarding kserv 2.10 on konflux

---

config/overlays/odh/params.env

Fixes #
- Logs
**Checklist**:
```release-note
```

Adding tekton changes for 2.10

---

.tekton/kserve-agent-28-push.yaml
.tekton/kserve-controller-28-push.yaml
.tekton/kserve-router-28-push.yaml
.tekton/kserve-storage-initializer-28-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

update tekton push.yaml

---

.tekton/kserve-router-28-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

dummy commit for router

---

Dockerfile
agent.Dockerfile
python/storage-initializer.Dockerfile
router.Dockerfile

Cherrypick https://github.com/opendatahub-io/kserve/pull/362

replace upstream Dockerfiles with ubi dockerfiles.

---

.tekton/kserve-agent-210-push.yaml
.tekton/kserve-controller-210-push.yaml
.tekton/kserve-router-210-push.yaml
.tekton/kserve-storage-initializer-210-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

Addning floating tags fopr kserve-2.10

---

.tekton/kserve-agent-28-pull-request.yaml
.tekton/kserve-agent-28-push.yaml
.tekton/kserve-controller-28-pull-request.yaml
.tekton/kserve-controller-28-push.yaml
.tekton/kserve-router-28-pull-request.yaml
.tekton/kserve-router-28-push.yaml
.tekton/kserve-storage-initializer-28-pull-request.yaml
.tekton/kserve-storage-initializer-28-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

Updating tekton to include floating tags 2.8

---

config/overlays/odh/params.env

Fixes #
- Logs
**Checklist**:
```release-note
```

update params.env to point to latest SHAs

---

.tekton/kserve-agent-28-push.yaml
.tekton/kserve-controller-28-push.yaml
.tekton/kserve-router-28-push.yaml
.tekton/kserve-storage-initializer-28-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

add missing annotation

---

.tekton/kserve-storage-initializer-211-pull-request.yaml
.tekton/kserve-storage-initializer-211-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

Red Hat Konflux update kserve-storage-initializer-211

---

.tekton/kserve-storage-initializer-211-pull-request.yaml
.tekton/kserve-storage-initializer-211-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

updating ksi file

---

.tekton/kserve-agent-211-push.yaml
.tekton/kserve-controller-211-push.yaml
.tekton/kserve-router-211-push.yaml
.tekton/kserve-storage-initializer-211-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

Updating kserve

---

.tekton/kserve-test-hermetic-poc-pull-request.yaml
.tekton/kserve-test-hermetic-poc-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

Addming hermetic to test

---

.tekton/kserve-router-test-hermetic-poc-pull-request.yaml
.tekton/kserve-router-test-hermetic-poc-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

Adding hermetic changes in kserve router poc

---

.tekton/kserve-router-test-hermetic-poc-pull-request.yaml
.tekton/kserve-router-test-hermetic-poc-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

adding refetch input

---

.tekton/kserve-agent-hermetic-poc-pull-request.yaml
.tekton/kserve-agent-hermetic-poc-push.yaml
.tekton/kserve-controller-hermetic-test-pull-request.yaml
.tekton/kserve-controller-hermetic-test-push.yaml
.tekton/kserve-router-test-hermetic-poc-pull-request.yaml
.tekton/kserve-router-test-hermetic-poc-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

hermetic poc

---

.tekton/kserve-agent-211-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

restart kserv agent

---

.tekton/kserve-agent-211-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

dummy-commit

---

config/overlays/odh/params.env

Fixes #
- Logs
**Checklist**:
```release-note
```

updading SHA references for kserve in params.env for 2.12

---

.tekton/kserve-agent-hermetic-poc-pull-request.yaml
.tekton/kserve-agent-hermetic-poc-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

updated the hemetic changes

---

.tekton/kserve-agent-pull-request.yaml
.tekton/kserve-agent-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

Fix component name

---

.tekton/kserve-agent-hermetic-poc-pull-request.yaml
.tekton/kserve-agent-hermetic-poc-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

adding changes for hermetic pull and push

---

.tekton/kserve-agent-test-hermetic-poc-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

Test hermetic poc

---

.tekton/kserve-agent-test-hermetic-poc-pull-request.yaml
.tekton/kserve-agent-test-hermetic-poc-push.yaml
.tekton/kserve-controller-test-hermetic-poc-pull-request.yaml
.tekton/kserve-controller-test-hermetic-poc-push.yaml
.tekton/kserve-router-test-hermetic-poc-pull-request.yaml
.tekton/kserve-router-test-hermetic-poc-push.yaml
.tekton/kserve-storage-initializer-test-hermetic-poc-pull-request.yaml
.tekton/kserve-storage-initializer-test-hermetic-poc-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

updating all hermetic change

---

.tekton/kserve-agent-212-pull-request.yaml
.tekton/kserve-agent-212-push.yaml
.tekton/kserve-controller-212-pull-request.yaml
.tekton/kserve-controller-212-push.yaml
.tekton/kserve-router-212-pull-request.yaml
.tekton/kserve-router-212-push.yaml
.tekton/kserve-storage-initializer-212-pull-request.yaml
.tekton/kserve-storage-initializer-212-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

Update tekton for kserve212

---

.tekton/kserve-agent-212-push.yaml
.tekton/kserve-controller-212-push.yaml
.tekton/kserve-router-212-push.yaml
.tekton/kserve-storage-initializer-212-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

correcting the tekton files

---

.tekton/kserve-controller-212-pull-request.yaml
.tekton/kserve-controller-212-push.yaml
.tekton/kserve-router-212-pull-request.yaml
.tekton/kserve-router-212-push.yaml
.tekton/kserve-storage-initializer-212-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

updating tekton to remove BASE_IMAGES_DIGESTS

---

.tekton/kserve-storage-initializer-212-pull-request.yaml
.tekton/kserve-storage-initializer-212-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

Adding catrust config to SI

---

.tekton/kserve-storage-initializer-212-pull-request.yaml
.tekton/kserve-storage-initializer-212-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

Base image removed

---

config/overlays/odh/params.env

Fixes #
- Logs
**Checklist**:
```release-note
```

updating controller sha

---

.tekton/kserve-storage-initializer-213-pull-request.yaml
.tekton/kserve-storage-initializer-213-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

Updating kserev init tekton

---

.tekton/kserve-controller-213-pull-request.yaml
.tekton/kserve-controller-213-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

Updating tekton file

---

config/overlays/odh/params.env

Fixes #
- Logs
**Checklist**:
```release-note
```

updating sha for 2.13

---

.tekton/kserve-storage-initializer-test-hermetic-poc-pull-request.yaml
.tekton/kserve-storage-initializer-test-hermetic-poc-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

updating new tekton

---

.tekton/kserve-storage-initializer-test-hermetic-poc-pull-request.yaml
.tekton/kserve-storage-initializer-test-hermetic-poc-push.yaml
python/rpms.in.yaml
python/rpms.lock.yaml
python/ubi.repo

Fixes #
- Logs
**Checklist**:
```release-note
```

enable rmp prefetching

---

.tekton/kserve-storage-initializer-test-hermetic-poc-pull-request.yaml
.tekton/kserve-storage-initializer-test-hermetic-poc-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

updating the rpm path

---

.tekton/kserve-storage-initializer-test-hermetic-poc-pull-request.yaml
.tekton/kserve-storage-initializer-test-hermetic-poc-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

adding prefetch for pip

---

.tekton/kserve-agent-test-hermetic-poc-pull-request.yaml
.tekton/kserve-agent-test-hermetic-poc-push.yaml
agent.Dockerfile

Fixes #
- Logs
**Checklist**:
```release-note
```

UPdating kserv agent changes

---

.tekton/kserve-agent-test-hermetic-poc-pull-request.yaml
.tekton/kserve-agent-test-hermetic-poc-push.yaml
rpms.in.yaml
rpms.lock.yaml
ubi.repo

Fixes #
- Logs
**Checklist**:
```release-note
```

Adding rpm changes for agent

---

python/kserve/poetry.lock

chore:  Update the poetry.lock files
so the dependency version gets updated, in this case the cryptography
one was updated as expected to the suggested one.
Fixes #
- Logs
1. Please confirm that if this PR changes any image versions, then that's the sole …

[RHOAIENG-14313] - KServe - Type Confusion [rhoai-2.13]

---

.tekton/kserve-si-hermetic-poc-pull-request.yaml
.tekton/kserve-si-hermetic-poc-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```

test hermetic poc for si

---

.tekton/kserve-agent-v2-18-pull-request.yaml
.tekton/kserve-agent-v2-18-push.yaml
.tekton/kserve-controller-v2-18-pull-request.yaml
.tekton/kserve-controller-v2-18-push.yaml
.tekton/kserve-router-v2-18-pull-request.yaml
.tekton/kserve-router-v2-18-push.yaml
.tekton/kserve-storage-initializer-v2-18-pull-request.yaml
.tekton/kserve-storage-initializer-v2-18-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```
- …

updating kserver-tekton

---

Dockerfiles/storage-initializer.Dockerfile.konflux

Fixes #
- Logs
**Checklist**:
```release-note
```
- …

Updated storage initializer dockerfile for ppc64le

---

.tekton/kserve-agent-v2-18-push.yaml
.tekton/kserve-controller-v2-18-push.yaml
.tekton/kserve-router-v2-18-push.yaml
.tekton/kserve-storage-initializer-v2-18-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```
- …

adding slack notification changes

---

config/configmap/inferenceservice.yaml
config/overlays/odh/inferenceservice-config-patch.yaml
hack/violation_exceptions.list
pkg/apis/serving/v1beta1/component.go
pkg/apis/serving/v1beta1/configmap.go
pkg/apis/serving/v1beta1/configmap_test.go
pkg/constants/constants.go
pkg/controller/v1beta1/inferenceservice/components/explainer.go
pkg/controller/v1beta1/inferenceservice/components/predictor.go
pkg/controller/v1beta1/inferenceservice/components/transformer.go
pkg/controller/v1beta1/inferenceservice/controller.go
pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go
pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go
pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go
pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go
pkg/controller/v1beta1/inferenceservice/utils/utils.go
pkg/openapi/openapi_generated.go
pkg/openapi/swagger.json
python/kserve/docs/V1beta1InferenceServicesConfig.md
python/kserve/kserve/models/v1beta1_inference_services_config.py

---------
Cherry pick : Use annotation instead of label to enable auth for RawDeployment 
Fixes #
- Logs
**Checklist**:
```release-note …
```

[Cherrypick] Use annotation instead of label to enable auth for RawDeployment(#519)

---

pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go
pkg/utils/utils.go
pkg/utils/utils_test.go

chore:  Fixes the reconcile loop to effectivelly update the EnvVars and replicas count.
Also address this issue: https://issues.redhat.com/browse/RHOAIENG-20634
Cherry-picks: https://github.com/opendatahub-io/kserve/pull/516
* review comments
---------
Fixes #
- Logs
**Special notes for your …

[RHOAIENG-20548] - Env variable removed from ISVC are not removed from predictor pod (#516)

---

config/overlays/test/kustomization.yaml
test/scripts/openshift-ci/run-e2e-tests.sh
test/scripts/openshift-ci/setup-e2e-tests.sh

What this PR does / why we need it:
Sync ODH v2.25 into main
[RHOAIENG-19212](https://issues.redhat.com/browse/RHOAIENG-19212)
Feature/Issue validation/testing:
All unit tests pass
Special notes for your reviewer:
Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.
Re-running failed tests
/rerun-all - rerun all failed workflows.
/rerun-workflow <workflow name> - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

ODH v2.25 sync into RHOAI main

---

.tekton/kserve-agent-v2-19-push.yaml
.tekton/kserve-controller-v2-19-push.yaml
.tekton/kserve-router-v2-19-push.yaml
.tekton/kserve-storage-initializer-v2-19-push.yaml

required to pass conforma after 1 april

[KONFLUX-2264,RHOAIENG-22379] add sast tasks to konflux

---

charts/kserve-resources/templates/clusterrole.yaml
cmd/router/main.go
config/overlays/odh/inferenceservice-config-patch.yaml
config/rbac/role.yaml
config/runtimes/kserve-tensorflow-serving.yaml
config/runtimes/kserve-torchserve.yaml
config/runtimes/kserve-tritonserver.yaml
pkg/constants/constants.go
pkg/controller/v1alpha1/inferencegraph/controller.go
pkg/controller/v1alpha1/inferencegraph/controller_test.go
pkg/controller/v1alpha1/inferencegraph/openshift_route_reconciler.go
pkg/controller/v1alpha1/inferencegraph/raw_ig.go
pkg/controller/v1alpha1/inferencegraph/raw_ig_test.go
pkg/controller/v1beta1/inferenceservice/components/explainer.go
pkg/controller/v1beta1/inferenceservice/components/predictor.go
pkg/controller/v1beta1/inferenceservice/components/transformer.go
pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go
pkg/controller/v1beta1/inferenceservice/reconcilers/raw/raw_kube_reconciler.go
pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go
pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler_test.go
pkg/webhook/admission/pod/storage_initializer_injector.go
pkg/webhook/validation/inferenceservice/inferenceservice_webhook_test.go
python/storage-initializer.Dockerfile
test/e2e/predictor/test_autoscaling.py
test/scripts/openshift-ci/run-e2e-tests.sh
test/scripts/openshift-ci/setup-e2e-tests.sh

What this PR does / why we need it:
Sync ODH v2.26 into main
[RHOAIENG-21097](https://issues.redhat.com/browse/RHOAIENG-21097)
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

ODH v2.26 sync into RHOAI main

---

Dockerfiles/storage-initializer.Dockerfile.konflux

Fixes #
- Logs
**Checklist**:
```release-note
```
- …

[RHOAIENG-7287] - storage initializer - update python to 3.11

---

.tekton/kserve-agent-v2-20-push.yaml
.tekton/kserve-controller-v2-20-push.yaml
.tekton/kserve-router-v2-20-push.yaml
.tekton/kserve-storage-initializer-v2-20-push.yaml

[KONFLUX-2264,RHOAIENG-22432] add sast tasks to konflux

---

config/overlays/odh/params.env

Cherrypick https://github.com/opendatahub-io/kserve/pull/555 
JIRA: https://issues.redhat.com/browse/RHOAIENG-23055

change oauth proxy image to be compatible with multi arch

---

Dockerfiles/storage-initializer.Dockerfile.konflux

Fixes #
- Logs
**Checklist**:
```release-note
```
- …

set unversioned python for alternatives

---

cmd/router/main.go
pkg/controller/v1alpha1/inferencegraph/raw_ig.go
pkg/controller/v1alpha1/inferencegraph/raw_ig_test.go

Cherry-pick of https://github.com/opendatahub-io/kserve/pull/566

[cherry-pick] add flag to control tls behavior for kserve router

---

Dockerfiles/storage-initializer.Dockerfile.konflux

Signed-off-by: Rehan Khan <Rehan.Khan7@ibm.com>

[RHOAIENG-24212] - storage initializer - Fix kserve storage initializer build error for s390x

---

pkg/webhook/admission/pod/agent_injector.go
pkg/webhook/admission/pod/agent_injector_test.go

Cherry-picks https://github.com/opendatahub-io/kserve/commit/778089a6e17690dd970ccb7bc7885105d1783a63

Enhance InjectAgent to Handle Only HTTPGet, TCP Readiness Probes (#4012)

---

Dockerfiles/agent.Dockerfile.konflux
Dockerfiles/controller.Dockerfile.konflux
Dockerfiles/router.Dockerfile.konflux
Dockerfiles/storage-initializer.Dockerfile.konflux

replaces https://github.com/red-hat-data-services/kserve/pull/1501
replaces https://github.com/red-hat-data-services/kserve/pull/1488
replaces https://github.com/red-hat-data-services/kserve/pull/1502

update to ubi9 in konflux dockerfiles

---

Dockerfiles/storage-initializer.Dockerfile.konflux
python/storage-initializer.Dockerfile

cherry-pick: https://github.com/red-hat-data-services/kserve/pull/1625
Fixes #
- Logs
**Checklist**:
```release-note
```
**Re-running …

[CherryPick] update pip version

---

Dockerfiles/storage-initializer.Dockerfile.konflux
python/storage-initializer.Dockerfile

[cherry-pick] https://github.com/opendatahub-io/kserve/pull/685
Fixes #
- Logs
**Checklist**:
```release-note
```
**Re-running failed …

[Cherry-pick] update pip version

---

Dockerfiles/agent.Dockerfile.konflux
Dockerfiles/controller.Dockerfile.konflux
Dockerfiles/router.Dockerfile.konflux

kserve now uses golang version 1.23.6, requiring the go-toolset:1.23 image to be used in konflux dockerfiles
Fixes #
**Checklist**:
```release-note
NONE
```
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

updating go-toolset to 1.23 in konflux dockerfiles

---

Dockerfiles/agent.Dockerfile.konflux
Dockerfiles/controller.Dockerfile.konflux
Dockerfiles/router.Dockerfile.konflux

kserve now uses golang version 1.23.6, requiring the go-toolset:1.23 image to be used in konflux dockerfiles
Fixes #
**Checklist**:
```release-note
NONE
```
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.

updating go-toolset to 1.23 in konflux dockerfiles 

---

pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go

Fixes constant loop between odh-model-controller and kserve-controller in serverless mode. 
See ticket for testing instructions
- Logs
**Checklist**:
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one …

RHOAIENG-30193-fixed-constant-looping cherry pick

---

pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go

Fixes constant loop between odh-model-controller and kserve-controller in serverless mode. 
See ticket for testing instructions
- Logs
**Checklist**:
- `/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one …

RHOAIENG-30193-fixed-constant-looping

---

.tekton/kserve-local-model-hermatic-pull-request.yaml
.tekton/kserve-local-model-hermatic-push.yaml

Fixes #
- Logs
**Checklist**:
```release-note
```
- …

tekton changes for hermetic

---

Dockerfiles/localmodel.Dockerfile.konflux

Fixes #
- Logs
**Checklist**:
```release-note
```
- …

removing cachi2 dependency

---

Dockerfiles/localmodel.Dockerfile.konflux

Fixes #
- Logs
**Checklist**:
```release-note
```
- …

updating dockerfile
